# Generated by Django 3.1.2 on 2020-11-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('course_cover', models.ImageField(blank=True, default=None, null=True, upload_to='Uploaded/CoursePoster')),
                ('capacity', models.IntegerField(default=10)),
                ('about_course', models.TextField(null=True, verbose_name='about course')),
                ('course_url', models.URLField(blank=True, db_index=True, default=None, max_length=128, verbose_name='course link')),
                ('grade', models.IntegerField(choices=[(1, 'class 1'), (2, 'class 2'), (3, 'class 3'), (4, 'class 4'), (5, 'class 5'), (6, 'class 6'), (7, 'class 7'), (8, 'class 8'), (9, 'class 9'), (10, 'class 10'), (11, 'class 11'), (12, 'class 12')], default=1)),
            ],
        ),
    ]
