# Generated by Django 3.1.2 on 2020-11-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_url',
        ),
    ]
