# Generated by Django 3.1.2 on 2020-11-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_course_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_url',
            field=models.URLField(blank=True, db_index=True, default=None, max_length=128, verbose_name='course link'),
        ),
    ]
