# Generated by Django 3.1.2 on 2020-11-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_course_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_url',
            field=models.URLField(blank=True, default=None, max_length=128, null=True, verbose_name='course link'),
        ),
    ]
