# Generated by Django 3.1.2 on 2020-10-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20201031_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name='first name'),
        ),
    ]
