# Generated by Django 3.1.2 on 2020-11-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Semail',
            field=models.EmailField(max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='about',
            field=models.TextField(null=True, verbose_name='about you'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Uploaded/TeacherAvatar'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='type',
            field=models.CharField(choices=[(1, 'SchoolTeacher'), (2, 'Student'), (3, 'Consultant'), (4, 'Select')], default=4, max_length=1),
        ),
    ]
