# Generated by Django 3.1.2 on 2020-11-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20201105_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('poster', models.ImageField(blank=True, default=None, null=True, upload_to='Uploaded/CoursePoster')),
                ('capacity', models.IntegerField()),
                ('students', models.ManyToManyField(related_name='subscription', to='Users.Student')),
            ],
        ),
    ]
