# Generated by Django 3.1.2 on 2020-11-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_course_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(default=10),
        ),
    ]
