# Generated by Django 3.1.2 on 2020-11-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_auto_20201107_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_url',
            field=models.URLField(blank=True, max_length=128, unique=True, verbose_name='Course link'),
        ),
    ]
