# Generated by Django 3.1.2 on 2020-11-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_auto_20201110_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_url',
            field=models.URLField(blank=True, db_index=True, max_length=128, verbose_name='Course link'),
        ),
    ]
