# Generated by Django 3.1.2 on 2020-11-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default=None, null=True, upload_to='Uploaded/TeacherAvatar')),
                ('teacher_type', models.CharField(choices=[(1, 'SchoolTeacher'), (2, 'Student'), (3, 'Consultant'), (4, 'Select')], default=4, max_length=1)),
                ('scholar_email', models.EmailField(max_length=254, null=True, verbose_name='email address')),
                ('personal_description', models.TextField(null=True, verbose_name='about you')),
                ('academy_name', models.CharField(default=None, max_length=200, null=True, verbose_name='academy name')),
                ('work_experience', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
