# Generated by Django 3.1.3 on 2020-11-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0002_teacher_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='scholar_email',
            new_name='Student_email',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='profile_picture',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='personal_description',
            new_name='bio_description',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='academy_name',
            field=models.CharField(max_length=200, null=True, verbose_name='academy name'),
        ),
    ]
