# Generated by Django 3.1.2 on 2020-11-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0003_auto_20201114_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='bio_description',
            new_name='personal_description',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='avatar',
            new_name='profile_picture',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Student_email',
            new_name='scholar_email',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='type',
            new_name='teacher_type',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='academy_name',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='academy name'),
        ),
    ]
